openapi: 3.0.3
info:
  title: API Federation of Agricultural Collectives
  version: 1.0.0
  description: API for management and digitalization of agricultural collective federation processes in Madagascar.

servers:
  - url: https://localhost:8080

paths:
  /collectives/{collectiveId}/accounts:
    get:
      summary: Consult the accounts status (Cash, Banks, Mobile Money)
      operationId: getAccounts
      parameters:
        - $ref: '../components/parameters.yaml#/collectiveIdParam'
      responses:
        '200':
          description: List of accounts and their balances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../components/schemas.yaml#/Account'
    
    post:
      summary: Add a new account to the collective
      operationId: addAccount
      parameters:
        - $ref: '../components/parameters.yaml#/collectiveIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/schemas.yaml#/Account'
      responses:
        '201':
          description: Account created (Note only one CASH account permitted)