openapi: 3.0.3
info:
  title: API Fédération de Collectivités Agricoles
  version: 1.0.0
  description: API de gestion pour la digitalisation des processus de la fédération des collectivités agricoles à Madagascar.

servers:
  -url: https://localhost:8080

paths:
  /collectivites/{collectiviteId}/comptes:
    get:
      summary: Consulter la situation des comptes (Caisse, Banques, Mobile Money)
      operationId: getComptes
      parameters:
        - $ref: '#/components/parameters/collectiviteIdParam'
      responses:
        '200':
          description: Liste des comptes et leurs soldes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Compte'
    
    post:
      summary: Ajouter un nouveau compte à la collectivité
      operationId: addCompte
      parameters:
        - $ref: '#/components/parameters/collectiviteIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Compte'
      responses:
        '201':
          description: Compte créé (Note un seul compte de type CAISSE permis)