openapi: 3.0.3
info:
  title: API Fédération de Collectivités Agricoles
  version: 1.0.0
  description: API de gestion pour la digitalisation des processus de la fédération des collectivités agricoles à Madagascar.

servers:
  -url: https://localhost:8080

paths:
  /collectivites/{collectiviteId}/cotisations:
    post:
      summary: Enregistrer le paiement d'une cotisation
      operationId: addCotisation
      parameters:
        - $ref: '#/components/parameters/collectiviteIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cotisation'
      responses:
        '201':
          description: Cotisation enregistrée