openapi: 3.0.3
info:
  title: API Fédération de Collectivités Agricoles
  version: 1.0.0
  description: API de gestion pour la digitalisation des processus de la fédération des collectivités agricoles à Madagascar.

servers:
  -url: https://localhost:8080

paths:
  /activites/{activiteId}/presences:
    post:
      summary: Enregistrer la fiche de présence d'une activité
      operationId: recordPresences
      parameters:
        - name: activiteId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FichePresence'
      responses:
        '200':
          description: Présences enregistrées